<?php

namespace Database\Seeders;

use App\Models\AcUnit;
use App\Models\Ruangan;
use App\Models\RumahSakit;
use Illuminate\Database\Seeder;

class RsMataSeeder extends Seeder
{
    public function run(): void
    {
        $rsMata = RumahSakit::create([
            'nama' => 'RS Mata',
            'alamat' => 'Surabaya',
        ]);

        $gedungA = [
            ['Split','Daikin','2 PK','Ex Poli 1','1',0],
            ['Split','Daikin','2 PK','Ex Poli 1','1',0],
            ['Split','Daikin','2 PK','Ex Poli 2','1',0],
            ['Split','Daikin','2 PK','Ex Poli 2','1',0],
            ['Split','Panasonic','2 PK','Ex Poli 3','1',0],
            ['Split','Sharp','1 PK','Ex Poli 3','1',0],
            ['Split','Daikin','2 PK','Ex Poli 4','1',0],
            ['Split','Daikin','2 PK','Ex Poli 4','1',0],
            ['Split','Daikin','2 PK','Poli 5','1',6],
            ['Split','Daikin','2 PK','Poli 5','1',6],
            ['Split','Daikin','2 PK','Poli 6 Lab','1',6],
            ['Split','Daikin','2 PK','Ex Poli 7','1',0],
            ['Split','Daikin','2 PK','Ex Poli 7','1',0],
            ['Split','Daikin','2 PK','Laundry','1',6],
            ['Split','Daikin','2 PK','Laundry','1',6],
            ['Split','Daikin','2 PK','Depo Farmasi','1',12],
            ['Split','Polytron','2 PK','Ex IGD Lama','1',6],
            ['Split','Daikin','2 PK','Lab pengambilan sample','1',6],
            ['Split','Daikin','2 PK','Rekam Medik Admin','1',6],
            ['Split','Daikin','2 PK','Rekam Medik Dokumen','1',6],
            ['Split','Daikin','1 PK','Kasir','1',6],
            ['Split','Daikin','2 PK','Loket','1',6],
            ['Split','Honsu','2 PK','CSSD Kassa','1',12],
            ['Split','Daikin','2 PK','CSSD Getting','1',12],
            ['Split','Daikin','2 PK','CSSD Getting','1',12],
            ['Split','Daikin','2 PK','CSSD Decon','1',12],
            ['Split','Panasonic','1 PK','CSSD BHP','1',12],
            ['Split','Daikin','2 PK','CSSD Packing','1',12],
            ['Split','Daikin','1 PK','R. Plasma','1',12],
            ['Split','Daikin','2 PK','Ruang Jaga D.U / VIP','1',6],
            ['Split','Daikin','2 PK','Ex BPJS/penjaminan','1',0],
            ['Split','Panasonic','1 PK','Pos Satpam','1',6],
            ['Cassete','Daikin','5 PK','Lobby Gedung Lama','1',6],
            ['Stand AC','Changhong','5 PK','Lobby gedung lama','1',6],
            ['Stand AC','Daikin','5 PK','Lobby Gedung Baru','1',6],
            ['Stand AC','Daikin','5 PK','Lobby Gedung Baru','1',6],
            ['Stand AC','Daikin','5 PK','Lobby Gedung Baru','1',6],
            ['Split','Daikin','1 PK','R. VIP I Gedung Baru','1',6],
            ['Split','Daikin','1 PK','R. Tindakan Gedung Baru','1',6],
            ['Split','Daikin','1 PK','R. Refraksi I Gedung Baru','1',6],
            ['Split','Daikin','1 PK','R. Lasik II Gedung Baru','1',6],
            ['Splitdak','LG','5 PK','Lasik','1',6],
            ['Split','Daikin','2 PK','Lasik','1',6],
            ['Split','Daikin','2 PK','Lasik','1',6],
            ['Split','Daikin','2 PK','R. Tunggu Lasik','1',6],
            ['Split','Daikin','2 PK','Lasik (Pre Lasik Dalam)','1',6],
            ['Split','Daikin','2 PK','Lasik (Pre Lasik Dalam)','1',6],
            ['Split','Daikin','2 PK','Poli vip diagnostic','1',6],
            ['Cassete','Daikin','5 PK','Lorong Lasik','1',6],
            ['Split','Daikin','2 PK','R. Ganti Dokter Lasik','1',6],
            ['Split','Daikin','2 PK','Masjid','1',4],
            ['Split','Daikin','2 PK','Masjid','1',4],
            ['Split','Daikin','2 PK','Masjid','1',4],
            ['Split','Panasonic','1 PK','Masjid','1',4],
            ['Split','Gree','2 PK','Masjid','1',4],
            ['Split','Daikin','2 PK','R. Tunggu IGD','1',6],
            ['Split','Daikin','1 PK','R. Perawat IGD','1',6],
            ['Split','Daikin','1 PK','R. Dokter IGD','1',6],
            ['Split','Daikin','2 PK','R. Tindakan IGD','1',6],
            ['Split','Daikin','2 PK','R. Tindakan IGD','1',6],
            ['Split','Daikin','2 PK','CCTV','2',6],
            ['Split','Daikin','2 PK','CCTV','2',6],
            ['Split','Daikin','2 PK','Kris Kls 1 laki-laki','2',4],
            ['Split','Daikin','2 PK','Kris Kls 1 Perempuan','2',4],
            ['Split','Daikin','2 PK','Kris Kls 2 laki-laki','2',4],
            ['Split','Daikin','2 PK','Kris Kls 2 Perempuan','2',4],
            ['Split','Daikin','2 PK','Kris Kls 3 laki-laki','2',4],
            ['Split','Daikin','2 PK','Kris Kls 3 laki-laki','2',4],
            ['Split','Daikin','2 PK','Kris Kls 3 Perempuan','2',4],
            ['Split','Daikin','2 PK','Kris Kls 3 Perempuan','2',4],
            ['Split','Daikin','2 PK','R.Jaga Dokter Kris','2',4],
            ['Split','Daikin','2 PK','R.server','2',4],
            ['Split','Daikin','2 PK','R.Panel','2',4],
            ['Split','Panasonic','1 PK','R.Gizi','2',4],
            ['Cassete','Daikin','5 PK','Koridor Kris Tengah','2',4],
            ['Cassete','Daikin','5 PK','Koridor Kris Tengah','2',4],
            ['Cassete','Daikin','5 PK','Koridor Kris Tengah','2',4],
            ['Cassete','Daikin','5 PK','Koridor Kris Tengah','2',4],
            ['Cassete','Daikin','5 PK','Koridor Kris Tengah','2',4],
            ['Cassete','Daikin','2.5 PK','Kris Vip laki-laki','2',4],
            ['Cassete','Daikin','2.5 PK','Kris Vip Perempuan','2',4],
            ['Cassete','Daikin','2.5 PK','Kris VViP laki-laki','2',4],
            ['Cassete','Daikin','3 PK','Kris VViP Perempuan','2',4],
            ['Cassete','Daikin','2.5 PK','R.Tindakan Kris','2',4],
            ['Cassete','Daikin','2.5 PK','R.Tindakan Kris','2',4],
            ['Cassete','Daikin','2.5 PK','R.Dispensing Kris','2',4],
            ['Cassete','Daikin','5 PK','Koridor Ranap depan','2',4],
            ['Cassete','Daikin','5 PK','Koridor Ranap Blakang','2',4],
            ['Cassete','Daikin','5 PK','Koridor depan nurse station','2',4],
            ['Cassete','LG','5 PK','R.Pemeriksaan Ranap','2',4],
            ['Cassete','LG','5 PK','R. Alamanda','2',4],
            ['Cassete','LG','5 PK','R.Bougenvill','2',4],
            ['Cassete','LG','5 PK','R.Camelia','2',4],
            ['Cassete','LG','5 PK','R.Dahlia','2',4],
            ['Cassete','LG','5 PK','R.Edelwais','2',4],
            ['Splitduct','LG','5 PK','HCU','2',4],
            ['Splitduct','LG','5 PK','R.Flamboyan','2',4],
            ['Split','LG','2 PK','R.Perawat HCU','2',4],
            ['Split','LG','2 PK','R.Perawat HCU','2',4],
            ['Split','LG','2 PK','R.Nurse station Ranap','2',4],
            ['Split','Panasonic','1 PK','Panel Ranap','2',4],
            ['Cassete','Daikin','5 PK','Ex Komite Medis','2',6],
            ['Split','Daikin','1 PK','Ex White Lab','2',6],
            ['Cassete','Daikin','5 PK','Komite Keperawatan','2',6],
            ['Cassete','Daikin','5 PK','Lorong Lift','2',6],
            ['Cassete','Daikin','5 PK','RR OKA','2',12],
            ['Cassete','Daikin','5 PK','Ruang Lorong OKA','2',12],
            ['Cassete','Daikin','5 PK','R. HCU','2',12],
            ['Split','Daikin','1 PK','R. Ganti Pria OKA','2',12],
            ['Split','Daikin','2 PK','R.Tunggu HCU','2',12],
            ['Split','Daikin','1 PK','R. Ganti Wanita OKA','2',12],
            ['Split','Panasonic','2 PK','R. Oka 3','2',12],
            ['Split','Daikin','1 PK','R. UPS oka L.2','2',12],
            ['Split','Daikin','2 PK','Gudang non medis','3',6],
            ['Split','Daikin','2 PK','Adm Logistik','3',6],
            ['Split','Daikin','2 PK','Logistik Dalam','3',6],
            ['Split','Daikin','2 PK','B3 Logistik','3',6],
            ['Split','Daikin','2 PK','Logistik Dalam','3',6],
            ['Split','Daikin','2 PK','R. Tunggu OKA Luar','3',12],
            ['Split','Daikin','2 PK','R. Tunggu OKA Luar','3',12],
            ['Split','Daikin','2 PK','PreOp OKA','3',12],
            ['Split','Daikin','3 PK','PreOp OKA','3',12],
            ['Split','Daikin','2 PK','Logistic OKA Dalam','3',12],
            ['Cassete','Mc Quay','5 PK','R. BHP OKA Dalam','3',12],
            ['Cassete','Mc Quay','2 PK','R. Tunggu OKA Dalam','3',12],
            ['Cassete','Mc Quay','2 PK','R. Ganti / Perawat / Dokter','3',12],
            ['Cassete','Mc Quay','2 PK','R. Admin OKA','3',12],
            ['Cassete','Mc Quay','2 PK','Odisey RR OKA','3',12],
            ['Cassete','Mc Quay','2 PK','Odisey RR OKA','3',12],
            ['Cassete','Mc Quay','2 PK','Odisey RR Kecil OKA','3',12],
            ['Cassete','Mc Quay','2 PK','Pre Med OKA','3',12],
            ['Cassete','Mc Quay','2 PK','BHP OKA','3',12],
            ['Cassete','Mc Quay','2 PK','Lorong Dalam OKA','3',12],
            ['Cassete','Mc Quay','2 PK','Lorong Dalam OKA','3',12],
            ['Cassete','Mc Quay','2 PK','Lorong Dalam OKA','3',12],
            ['Cassete','Mc Quay','2 PK','R. Baru OKA Belakang','3',12],
            ['Cassete','Mc Quay','2 PK','R. Baru OKA Belakang','3',12],
            ['Cassete','Mc Quay','2 PK','R. Baru OKA Belakang','3',12],
            ['Cassete','Mc Quay','2 PK','R. Baru OKA Belakang','3',12],
            ['Cassete','Mc Quay','2 PK','R. Baru OKA Belakang','3',12],
            ['Cassete','Mc Quay','2 PK','R. Baru OKA Belakang','3',12],
            ['Cassete','Mc Quay','2 PK','R. Baru OKA Belakang','3',12],
            ['Split','Daikin','1 PK','R. Istirahat Pasien VIP','3',12],
            ['Split','Panasonic','2 PK','Pre-op oka L.3','3',12],
            ['Split','Daikin','1 PK','Panel oka L.3','3',12],
            ['Split','Daikin','2 PK','Kontrol Lift','4',12],
            ['Split','Daikin','2 PK','Kontrol Lift','4',12],
            ['AHU','Daikin','10 PK','Oka 1','3',12],
            ['AHU','Daikin','10 PK','Oka 2','3',12],
            ['AHU','Daikin','10 PK','Oka 3','3',12],
            ['AHU','Daikin','10 PK','Oka 4','3',12],
        ];

        $gedungB = [
            ['Cassete','Samsung','5 PK','Loby Lantai 1','1',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 1','1',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 1','1',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 1','1',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 1','1',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 1','1',4],
            ['Cassete','Samsung','5 PK','BPJS','1',4],
            ['Split','Samsung','2 PK','Farmasi','1',4],
            ['Split','Samsung','2 PK','Farmasi (R.Racik)','1',4],
            ['Split','Samsung','2 PK','Konsultasi Farmasi','1',4],
            ['Split','Samsung','2 PK','Farmasi','1',4],
            ['Cassete','Samsung','2 PK','Rekam Medis','1',4],
            ['Split','Samsung','2 PK','Adm lantai 1','1',4],
            ['Split','Samsung','2 PK','Koridor Depan Lift','1',4],
            ['Split','Samsung','2 PK','IPSRS','1',3],
            ['Split','Samsung','2 PK','Ruang Travo rsmm','1',3],
            ['Split','Samsung','2 PK','Ruang Kubikel PLN','1',3],
            ['Split','Samsung','2 PK','Ruang Kubikel PLN','1',3],
            ['Split','Samsung','2 PK','Kasir','1',4],
            ['Cassete','Samsung','5 PK','Koridor depan lift','2',4],
            ['Split','Samsung','2 PK','Koridor depan Lift pegawai','2',3],
            ['Cassete','Samsung','5 PK','Refraksi','2',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 2','2',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 2','2',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 2','2',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 2','2',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 2','2',4],
            ['Cassete','Samsung','2 PK','EED','2',4],
            ['Cassete','Samsung','2 PK','Rekontruksi','2',4],
            ['Cassete','Samsung','2 PK','Tindakan umum','2',4],
            ['Cassete','Samsung','2 PK','Koridor depan Lift','2',4],
            ['Cassete','Samsung','2 PK','Koridor depan Lift','2',4],
            ['Cassete','Samsung','2 PK','Koridor depan Lift','2',4],
            ['Cassete','Samsung','5 PK','Sky bridge','2',2],
            ['Cassete','Samsung','5 PK','Sky bridge','2',2],
            ['Cassete','Samsung','5 PK','Sky bridge','2',2],
            ['Cassete','Samsung','5 PK','Sky bridge','2',2],
            ['Cassete','Samsung','5 PK','Sky bridge','2',2],
            ['Cassete','Samsung','5 PK','Sky bridge','2',2],
            ['Cassete','Samsung','5 PK','Sky bridge','2',2],
            ['Split','Samsung','2 PK','Poli 2','2',4],
            ['Split','Samsung','2 PK','Poli 2','2',4],
            ['Split','Samsung','2 PK','Poli 2','2',4],
            ['Split','Samsung','2 PK','Poli 2','2',4],
            ['Split','Samsung','2 PK','R. Tindakan','2',4],
            ['Split','Samsung','2 PK','R. Low vision','2',4],
            ['Split','Samsung','2 PK','R. Low vision','2',4],
            ['Split','Samsung','2 PK','R. Farmasi','2',4],
            ['Cassete','Samsung','5 PK','Penjadwalan','3',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 3','3',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 3','3',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 3','3',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 3','3',4],
            ['Cassete','Samsung','5 PK','Loby Lantai 3','3',4],
            ['Cassete','Samsung','2 PK','R. Refraksi','3',4],
            ['Cassete','Samsung','2 PK','R. Refraksi','3',4],
            ['Cassete','Samsung','2 PK','R. Lab','3',4],
            ['Cassete','Samsung','2 PK','Koridor depan Lift','3',3],
            ['Cassete','Samsung','2 PK','Koridor depan Lift','3',3],
            ['Cassete','Samsung','2 PK','Koridor depan Lift','3',3],
            ['Split','Samsung','2 PK','Koridor depan Lift pegawai','3',3],
            ['Split','Samsung','2 PK','R. Penjadwalan','3',4],
            ['Split','Samsung','2 PK','Konsultasi PD','3',4],
            ['Split','Samsung','2 PK','Konsultasi PD','3',4],
            ['Split','Samsung','2 PK','R. Laser','3',4],
            ['Split','Samsung','2 PK','R. Post Op','3',4],
            ['Split','Samsung','2 PK','R. Glaukoma','3',4],
            ['Split','Samsung','2 PK','R. Glaukoma','3',4],
            ['Split','Samsung','2 PK','R. Glaukoma','3',4],
            ['Split','Samsung','2 PK','R. Glaukoma','3',4],
            ['Cassete','Samsung','5 PK','Loby lantai 4','4',4],
            ['Cassete','Samsung','5 PK','Loby lantai 4','4',4],
            ['Cassete','Samsung','5 PK','Loby lantai 4','4',4],
            ['Cassete','Samsung','5 PK','Loby lantai 4','4',4],
            ['Cassete','Samsung','2 PK','R. Diagnostic','4',4],
            ['Cassete','Samsung','2 PK','R. Diagnostic','4',4],
            ['Cassete','Samsung','2 PK','R. HFA','4',4],
            ['Split','Samsung','2 PK','Assesment Perawat','4',3],
            ['Split','Samsung','2 PK','Laktasi','4',3],
            ['Cassete','Samsung','2 PK','Depan lorong lift barang','4',3],
            ['Cassete','Samsung','2 PK','Depan lorong lift barang','4',3],
            ['Split','Samsung','2 PK','Farmasi lt.4','4',4],
            ['Cassete','Samsung','2 PK','Koridor arah lift barang','4',3],
            ['Cassete','Samsung','2 PK','Gudang berkas inaktif','4',3],
            ['Cassete','Samsung','2 PK','Koridor depan lift','4',4],
            ['Cassete','Samsung','2 PK','Koridor depan lift','4',4],
            ['Cassete','Samsung','2 PK','Koridor depan lift','4',4],
            ['Cassete','Samsung','5 PK','Loby poli eksekutif','4',2],
            ['Cassete','Samsung','5 PK','Loby poli eksekutif','4',2],
            ['Cassete','Samsung','5 PK','Loby poli eksekutif','4',2],
            ['Cassete','Samsung','5 PK','Loby poli eksekutif','4',2],
            ['Cassete','Samsung','5 PK','Loby poli eksekutif','4',2],
            ['Cassete','Samsung','5 PK','Loby poli eksekutif','4',2],
            ['Cassete','Samsung','5 PK','Loby poli eksekutif','4',2],
            ['Cassete','Samsung','2 PK','Laboratorium','4',4],
            ['Split','Samsung','2 PK','Ruang Transit','4',4],
            ['Split','Samsung','2 PK','Konsultasi','4',4],
            ['Split','Samsung','2 PK','Koridor depan lift pegawai','4',4],
            ['Cassete','Samsung','5 PK','Tindakan 4.01 - 4.05','4',4],
            ['Cassete','Samsung','2 PK','Tindakan 4.01 - 4.02','4',4],
            ['Cassete','Samsung','2 PK','Tindakan 4.01 - 4.02','4',4],
            ['Split','Samsung','2 PK','Penjamin','4',4],
            ['Split','Samsung','2 PK','Poli 4 vip','4',2],
            ['Split','Samsung','2 PK','Poli 4 vip','4',2],
            ['Split','Samsung','2 PK','Poli 4 vip','4',2],
            ['Split','Samsung','2 PK','Poli 4 vip','4',2],
            ['Cassete','Samsung','2 PK','R. Refraksi','4',4],
            ['Cassete','Samsung','2 PK','R. Refraksi','4',4],
            ['Cassete','Samsung','2 PK','Koridor lift pegawai','4',4],
            ['Cassete','Samsung','2 PK','Koridor depan mushollah','4',4],
            ['Split','Samsung','2 PK','R. Retina 1','4',4],
            ['Split','Samsung','2 PK','R. Retina 2','4',4],
            ['Split','Samsung','2 PK','R. Retina 3','4',4],
            ['Split','Samsung','2 PK','R. Retina 4','4',4],
            ['Split','Samsung','2 PK','R. Retina 5','4',4],
            ['Split','Samsung','2 PK','R. Retina 6','4',4],
            ['Cassete','Samsung','5 PK','Loby lantai 5','5',3],
            ['Cassete','Samsung','5 PK','Loby lantai 5','5',3],
            ['Cassete','Samsung','5 PK','Loby lantai 5','5',3],
            ['Cassete','Samsung','5 PK','R. Direktur','5',3],
            ['Cassete','Samsung','5 PK','R. Direktur','5',3],
            ['Cassete','Samsung','5 PK','R. Manajemen','5',3],
            ['Cassete','Samsung','5 PK','R. Manajemen','5',3],
            ['Cassete','Samsung','5 PK','R. Manajemen','5',3],
            ['Cassete','Samsung','5 PK','R. Manajemen','5',3],
            ['Cassete','Samsung','5 PK','R. Manajemen','5',3],
            ['Cassete','Samsung','5 PK','R. Manajemen','5',3],
            ['Cassete','Samsung','5 PK','R. Rapat 1','5',3],
            ['Cassete','Samsung','5 PK','R. Rapat 2','5',3],
            ['Cassete','Samsung','5 PK','Command center','5',3],
            ['Cassete','Samsung','5 PK','Command center','5',3],
            ['Cassete','Samsung','2 PK','Command center','5',3],
            ['Cassete','Samsung','2 PK','R. CCTV','5',4],
            ['Cassete','Samsung','2 PK','R. Koridor depan mushollah','5',3],
            ['Cassete','Samsung','2 PK','R. Koridor depan mushollah','5',3],
            ['Cassete','Samsung','5 PK','Perpustakaan','5',2],
            ['Cassete','Samsung','5 PK','Manajemen bersama','5',2],
            ['Cassete','Samsung','5 PK','Manajemen bersama','5',2],
            ['Cassete','Samsung','5 PK','Gudang Arsip Keuangan','5',2],
            ['Cassete','Samsung','2 PK','Komite Ppi','5',2],
            ['Cassete','Samsung','2 PK','Komite Etik dan Spi','5',2],
            ['Cassete','Samsung','2 PK','Komite Nakes dll','5',2],
            ['Cassete','Samsung','2 PK','Komite Keperawatan','5',2],
            ['Cassete','Samsung','2 PK','Komite Medik','5',2],
            ['Cassete','Samsung','2 PK','Koridor arah lift barang','5',3],
            ['Cassete','Samsung','2 PK','Koridor arah lift barang','5',3],
            ['Split','Samsung','2 PK','R. Direktur','5',3],
            ['Split','Samsung','2 PK','R. Kabid 1','5',3],
            ['Split','Samsung','2 PK','R. Kabid 2','5',3],
            ['Split','Samsung','2 PK','R. Kabid 3','5',3],
            ['Split','Samsung','2 PK','R. Kasie 1','5',3],
            ['Split','Samsung','2 PK','R. Kasie 2','5',3],
            ['Split','Samsung','2 PK','R. Kasie 3','5',3],
            ['Split','Samsung','2 PK','R. Kasie 4','5',3],
            ['Split','Samsung','2 PK','R. Kasie 5','5',3],
            ['Split','Samsung','2 PK','R. Kasie 6','5',3],
            ['Split','Samsung','2 PK','R. Gudang Pengadaan','5',2],
            ['Split','Samsung','2 PK','R. Gudang Manajemen','5',2],
            ['Split','Samsung','1 PK','Command center','5',3],
            ['Split','Samsung','2 PK','Laktasi','5',2],
            ['Split','Samsung','2 PK','Koridor depan lift pegawai','5',3],
            ['Cassete','Samsung','5 PK','Mushollah','5',3],
            ['Cassete','Samsung','5 PK','Mushollah','5',3],
            ['Split','Samsung','2 PK','Mushollah','4',3],
            ['Split','Samsung','2 PK','Mushollah','4',3],
            ['Split','Samsung','2 PK','Mushollah','3',3],
            ['Split','Samsung','2 PK','Mushollah','3',3],
            ['Split','Samsung','2 PK','Mushollah','2',3],
            ['Split','Samsung','2 PK','Mushollah','2',4],
            ['Split','Panasonic','1 PK','Power house','1',4],
            ['Split','Panasonic','1 PK','Power house','1',4],
            ['Split','Daikin','1 PK','Ruang FCC','1',4],
            ['Split','Panasonic','1 PK','Gudang Ipal','1',3],
            ['Cassete','Samsung','3 PK','Ruang pertemuan rooftop','6',2],
            ['Cassete','Samsung','3 PK','Ruang pertemuan rooftop','6',2],
            ['Cassete','Samsung','3 PK','Ruang pertemuan rooftop','6',2],
            ['Cassete','Samsung','3 PK','Ruang pertemuan rooftop','6',2],
            ['Split','Samsung','2 PK','Mesin Lift Rooftop','6',4],
            ['Split','Samsung','2 PK','Mesin Lift Rooftop','6',4],
            ['Split','Samsung','2 PK','Mesin Lift LS','6',4],
            ['Split','Samsung','2 PK','Mesin Lift LP','6',4],
            ['Split','Samsung','2 PK','Mesin Lift LS','6',4],
            ['Split','Samsung','2 PK','Mesin Lift LP','6',4],
        ];

        // Extract unique room names and create Ruangan records
        $allRooms = collect(array_merge($gedungA, $gedungB))
            ->pluck(3)
            ->map(fn($name) => trim($name))
            ->unique()
            ->values();

        foreach ($allRooms as $roomName) {
            Ruangan::create([
                'rumah_sakit_id' => $rsMata->id,
                'nama' => $roomName,
            ]);
        }

        foreach ($gedungA as $row) {
            AcUnit::create([
                'rumah_sakit_id' => $rsMata->id,
                'gedung' => 'Gedung A',
                'jenis_ac' => $row[0],
                'merk_ac' => $row[1],
                'kapasitas_pk' => $row[2],
                'ruangan' => $row[3],
                'lantai' => $row[4],
                'frekuensi_cuci' => $row[5],
            ]);
        }

        foreach ($gedungB as $row) {
            AcUnit::create([
                'rumah_sakit_id' => $rsMata->id,
                'gedung' => 'Gedung B',
                'jenis_ac' => $row[0],
                'merk_ac' => $row[1],
                'kapasitas_pk' => $row[2],
                'ruangan' => $row[3],
                'lantai' => $row[4],
                'frekuensi_cuci' => $row[5],
            ]);
        }
    }
}
